services:
  - docker

before_install:
  - docker pull eric7237cire/rgb
  - docker run -it -d --name build -v $TRAVIS_BUILD_DIR:/gitroot --env GITHUB_TOKEN=$GITHUB_TOKEN eric7237cire/rgb /bin/bash

script:
  - docker exec -ti build bash -c "mv /initial_build/rgb-solver/target /gitroot/rgb-solver/target &&  du --max-depth=1 -h /gitroot/rgb-solver/target"
  - docker exec -ti build bash -c "cd /gitroot/rgb-solver && cargo test --target x86_64-unknown-linux-gnu --lib --verbose"
  - docker exec -ti build bash -c "cd /gitroot/rgb-solver && wasm-pack build --release && cd pkg && npm link"
  - docker exec -ti build bash -c "cd /gitroot/web_worker && npm link && npm link rgb-solver && npm run build && npm run build-lib"
  - docker exec -ti build bash -c "cd /gitroot/grid-editor && npm ci"
  - docker exec -ti build bash -c "cd /gitroot/grid-editor && npm link web_worker && ls -al node_modules/web_worker"
  - docker exec -ti build bash -c "cd /gitroot/grid-editor && ng build --prod --base-href https://eric7237cire.github.io/rgb_delivery/"
  - docker exec -ti build bash -c "cd /gitroot/grid-editor && ngh --no-silent --dir dist/grid-editor --name='Travis CI' --email='314512+eric7237cire@users.noreply.github.com'"


after_script:
  - docker stop build

