matrix:
  include:
    - language: rust
      cache: cargo

      before_install:
        - cd rgb-solver

      # https://github.com/rustwasm/wasm-pack-template/blob/master/.travis.yml
      before_script:

        #- rustup target add wasm32-unknown-unknown
        #- curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

      script:
        #- cargo build --verbose --all
        - cargo test --target x86_64-unknown-linux-gnu --lib --verbose --all

        # - wasm-pack build

    - language: node_js

      node_js:
        - "9"
      dist: trusty
#      sudo: required
#      branches:
#        only:
#        - master
      before_script:
        - npm install -g @angular/cli
      script:
        - cd web_worker
        - npm install
        - ./node_modules/.bin/webpack
        - cp -r ./dist/* ../grid-editor/src/assets
        - cp ./worker/interface_types.ts ../grid-editor/src/app/typings/worker.ts
        - cd ../grid-editor
        - ng build --prod --base-href https://eric7237cire.github.io/rgb_delivery/