matrix:
  include:
    - language: rust
      cache: cargo

      before_install:
        - cd rgb-solver

      # https://github.com/rustwasm/wasm-pack-template/blob/master/.travis.yml
      before_script:

        #- rustup target add wasm32-unknown-unknown
        #- curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

      script:
        #- cargo build --verbose --all
        - cargo test --target x86_64-unknown-linux-gnu --lib --verbose --all

        # - wasm-pack build

    - language: node_js

      node_js:
        - "9"
      dist: trusty
      before_script:
        - npm install -g @angular/cli
      script:
        - cd web_worker
        - npm install
        - ./node_modules/.bin/webpack
        - npm link
        - cd ../grid-editor
        - npm link web_worker
        - npm install
        - ng build --prod --base-href https://eric7237cire.github.io/rgb_delivery/
        - ls -l ./dist/grid-editor/assets

      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        # from root
        local_dir: grid-editor/dist/grid-editor
        verbose: true
        on:
          all_branches: true
